version: '3.8'

services:
  # PocketBase Backend для разработки
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile.pocketbase
    container_name: jab-pocketbase-dev
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pocketbase/pb_data
      - ./pb_migrations:/pocketbase/pb_migrations
      - ./pocketbase:/pocketbase/pocketbase
    environment:
      - PB_DATA_DIR=/pocketbase/pb_data
    networks:
      - jab-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Next.js Frontend для разработки
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jab-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_POCKETBASE_URL=http://localhost:8090
    depends_on:
      pocketbase:
        condition: service_healthy
    networks:
      - jab-network
    command: npm run dev

volumes:
  pocketbase_data:
    driver: local
  pocketbase_migrations:
    driver: local

networks:
  jab-network:
    driver: bridge
