version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.railway
    container_name: jab-frontend-railway
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_POCKETBASE_URL=http://pocketbase:8090
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - pocketbase
    networks:
      - jab-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile.pocketbase
    container_name: jab-pocketbase-railway
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      - PB_DATA_DIR=/pocketbase/pb_data
    networks:
      - jab-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  jab-network:
    driver: bridge
